#ifndef MONTANA_FFI_H
#define MONTANA_FFI_H

/* Generated by cbindgen from mt-bindings (network.rs/mdns.rs). Do not edit by hand -- SSOT is the Rust code. Regenerate: cbindgen --config cbindgen.toml crates/mt-bindings -o crates/mt-bindings/include/montana_ffi.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define ABI_VERSION 1

#define MT_MASTER_SEED_LEN 64

#define MT_MLDSA_SEED_LEN 32

#define MT_MLDSA_PUBKEY_SIZE 1952

#define MT_MLDSA_SECKEY_SIZE 4032

#define MT_MLDSA_SIG_SIZE 3309

#define MT_ACCOUNT_ID_LEN 32

#define MT_HISTORY_KEY_LEN 32

#define MT_MAX_MNEMONIC_BYTES 512

#define MT_MLKEM_SEED_LEN 64

#define MT_MLKEM_PUBKEY_SIZE 1184

#define MT_MLKEM_SECKEY_SIZE 2400

#define MT_MLKEM_CT_SIZE 1088

#define MT_MLKEM_SS_SIZE 32

#define MT_OK 0

#define MT_ERR_NULL_PTR -1

#define MT_ERR_INVALID_UTF8 -2

#define MT_ERR_MNEMONIC_WORD_COUNT -3

#define MT_ERR_MNEMONIC_UNKNOWN_WORD -4

#define MT_ERR_MNEMONIC_CHECKSUM -5

#define MT_ERR_KEYGEN_FAILED -6

#define MT_ERR_SIGN_FAILED -7

#define MT_ERR_VERIFY_FAILED -8

#define MT_ERR_BUFFER_TOO_SMALL -9

#define MT_ERR_KDF_FAILED -10

#define MT_ERR_ADDRESS_INVALID -13

#define MT_ERR_KEM_FAILED -11

#define MT_ERR_REPLAY -12

#define MT_ERR_PANIC -100

/**
 * Canonical suite_id for the ML-DSA-65 account keypair (spec §Suite registry).
 */
#define MT_SUITE_MLDSA65 1

/**
 * Opaque client handle (live QUIC connection to a postman/courier).
 * `pending` buffers the tail of a batched fetch: `subscribe_via_courier` is a destructive
 * batch-drain (the host hands over and drops ALL queue items at once), so the FFI must
 * keep the whole batch and hand it out one by one, otherwise items[1..] are lost (§206 "the
 * buffer never loses a message").
 */
typedef struct MtClient MtClient;

/**
 * Opaque mDNS daemon handle (keeps the service registration alive).
 */
typedef struct MtMdns MtMdns;

/**
 * Opaque handle of a live postman for the FFI. Holds the address, the loop task (for shutdown)
 * and MuqState (courier routes).
 */
typedef struct MtPostman MtPostman;

/**
 * Opaque Mainline DHT client handle (rendezvous).
 */
typedef struct RvDht RvDht;

/**
 * Opaque account_id<->wake_handle registry (phone postman).
 */
typedef struct WakeRegistry WakeRegistry;

/**
 * Announce this postman on the local network on port `port`. Returns a handle
 * (the daemon keeps the announcement alive) or null. `instance` is a C-string instance name.
 *
 * # Safety
 * `instance` is a valid C-string or null.
 */
MtMdns *mt_mdns_advertise(uint16_t port,
                          const char *instance);

/**
 * Discover Montana nodes on the local network within `timeout_ms`. Writes the found addresses to `out`
 * as an "ip:port\n"-separated ASCII string (capacity `out_cap`, null-terminated), returns
 * the number of nodes found (0 if none / on error).
 *
 * # Safety
 * `out` is a buffer of at least `out_cap` bytes or null.
 */
size_t mt_mdns_browse(uint32_t timeout_ms,
                         uint8_t *out,
                         size_t out_cap);

/**
 * Stop the announcement and release the handle.
 *
 * # Safety
 * `h` is a handle from `mt_mdns_advertise` or null; do not reuse.
 */
void mt_mdns_stop(MtMdns *h);

/**
 * Start a postman on `bind` (e.g. "0.0.0.0:0"). On success writes the actual
 * address (host:port) to `out_addr` (buffer of capacity `out_cap`, null-terminated) and returns
 * an opaque handle; on error returns null. The handle is released by `mt_postman_stop`.
 *
 * # Safety
 * `bind` is a valid C-string; `out_addr` is a buffer of at least `out_cap` bytes or null.
 */
MtPostman *mt_postman_start(const char *bind,
                            char *out_addr,
                            size_t out_cap);

/**
 * Stop the postman and release the handle. `h` is invalid after the call.
 *
 * # Safety
 * `h` is a handle from `mt_postman_start` or null; do not reuse.
 */
void mt_postman_stop(MtPostman *h);

/**
 * Port of a live postman (0 for a null handle) -- for diagnostics/tests.
 *
 * # Safety
 * `h` is a valid handle from `mt_postman_start` or null.
 */
uint16_t mt_postman_port(const MtPostman *h);

/**
 * Add a courier route: `overlay` (32 B host overlay address) → physical `target`
 * (host:port). Returns 0 on success, -1 on invalid arguments. Stage 3 relay model.
 *
 * # Safety
 * `h` is a valid handle; `overlay` points to 32 bytes; `target` is a C-string.
 */
int32_t mt_postman_add_route(const MtPostman *h,
                             const uint8_t *overlay,
                             const char *target);

/**
 * Write the postman ML-KEM pubkey (1184 B) to `out` (capacity `out_cap`). The client
 * uses it for a sealed deposit. Returns the bytes written (0 on error).
 *
 * # Safety
 * `h` is a valid handle; `out` is a buffer of at least `out_cap` bytes.
 */
size_t mt_postman_kem_pubkey(const MtPostman *h,
                                uint8_t *out,
                                size_t out_cap);

/**
 * Connect to a postman at `addr` (host:port). Returns a handle or null.
 *
 * # Safety
 * `addr` is a valid C-string.
 */
MtClient *mt_client_connect(const char *addr);

/**
 * Register a queue on host `host_overlay` (32 B) via the courier the client is
 * connected to. `host_kem` is the 1184 B host pubkey; `queue` is a serialized Queue
 * (`queue_len` bytes). Returns 0 on success, -1 on error.
 *
 * # Safety
 * `client` is a valid handle; `host_overlay` → 32 B; `host_kem` → 1184 B; `queue` → `queue_len` B.
 */
int32_t mt_client_register(const MtClient *client,
                           const uint8_t *host_overlay,
                           const uint8_t *host_kem,
                           const uint8_t *queue,
                           size_t queue_len);

/**
 * Register a queue DIRECTLY on the connected node (TAG_QUEUE_REGISTER, no courier). Self-host uses
 * this against its own node (loopback): the queue registers locally without any self-connection.
 * `queue` — serialized Queue (`queue_len` bytes). Returns 0 on success, -1 on error.
 *
 * # Safety
 * `client` — handle from `mt_client_connect`; `queue` → `queue_len` bytes.
 */
int32_t mt_client_register_direct(const MtClient *client,
                                  const uint8_t *queue,
                                  size_t queue_len);

/**
 * Release the client handle (closes the connection).
 *
 * # Safety
 * `c` is a handle from `mt_client_connect` or null; do not reuse.
 */
void mt_client_free(MtClient *c);

/**
 * Send message `msg` to queue `send_id` on host `host_overlay` via the courier
 * (two-hop deposit, sealed to the host ML-KEM key). Builds HostDeposit+signature+seal internally.
 * Single shard. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `client` is valid; `host_overlay`→32; `host_kem`→1184; `send_id`→32; `send_sk`→4032;
 * `msg_id`→16; `msg`→`msg_len`.
 */
int32_t mt_client_send(const MtClient *client,
                       const uint8_t *host_overlay,
                       const uint8_t *host_kem,
                       const uint8_t *send_id,
                       const uint8_t *send_sk,
                       const uint8_t *msg_id,
                       const uint8_t *msg,
                       size_t msg_len);

/**
 * Fetch one message from queue `recv_id` on host `host_overlay` via the courier.
 * Writes the ct of the first envelope to `out` (capacity `out_cap`), returns its length;
 * 0 if the queue is empty or on error.
 *
 * # Safety
 * `client` is valid; `host_overlay`→32; `host_kem`→1184; `recv_id`→32; `recv_sk`→4032;
 * `out`→`out_cap`.
 */
size_t mt_client_recv(const MtClient *client,
                         const uint8_t *host_overlay,
                         const uint8_t *host_kem,
                         const uint8_t *recv_id,
                         const uint8_t *recv_sk,
                         uint8_t *out,
                         size_t out_cap);

/**
 * Acknowledge receipt (DEV-049(a) §593): the host drops the buffer of queue recv_id. 0 = success.
 *
 * # Safety
 * `client` is valid; `host_overlay`→32; `host_kem`→1184; `recv_id`→32; `recv_sk`→4032.
 */
int32_t mt_client_ack(const MtClient *client,
                      const uint8_t *host_overlay,
                      const uint8_t *host_kem,
                      const uint8_t *recv_id,
                      const uint8_t *recv_sk);

/**
 * DEV-049(b): RS(k,n) multi-host send -- splits `msg` into `n` shards and deposits
 * one on each of the `n` hosts. Hosts are concatenated arrays: `host_overlays`
 * (n*32), `host_kems` (n*1184). Returns the number of successful deposits (durable at >= k),
 * -1 on error.
 *
 * # Safety
 * `client` is valid; `host_overlays`→`n*32`; `host_kems`→`n*1184`; `send_id`→32;
 * `send_sk`→4032; `msg_id`→16; `msg`→`msg_len`.
 */
int32_t mt_client_send_erasure(const MtClient *client,
                               const uint8_t *host_overlays,
                               const uint8_t *host_kems,
                               size_t n,
                               size_t k,
                               const uint8_t *send_id,
                               const uint8_t *send_sk,
                               const uint8_t *msg_id,
                               const uint8_t *msg,
                               size_t msg_len);

/**
 * DEV-049(b): RS(k,n) multi-host fetch -- collects shards from `n` hosts and reconstructs
 * from any `k`. Writes the reconstructed ct to `out`; returns its length (0 if fewer than k were collected /
 * on error; need > out_cap = buffer too small).
 *
 * # Safety
 * `client` is valid; `host_overlays`→`n*32`; `host_kems`→`n*1184`; `recv_id`→32;
 * `recv_sk`→4032; `out`→`out_cap`.
 */
size_t mt_client_recv_erasure(const MtClient *client,
                                 const uint8_t *host_overlays,
                                 const uint8_t *host_kems,
                                 size_t n,
                                 size_t k,
                                 const uint8_t *recv_id,
                                 const uint8_t *recv_sk,
                                 uint8_t *out,
                                 size_t out_cap);

/**
 * montana:// deep-link kind: 0 = bootstrap payload (montana://b/...), 1 = wallet address
 * (montana://mt...), -1 = parse error.
 *
 * # Safety
 * `link` is a valid C-string.
 */
int32_t mt_deeplink_kind(const char *link);


/**
 * For montana://b/<payload>: decodes QRBootstrap, writes current_endpoint
 * (SSRF-filtered, "host:port" ASCII) to `out`; returns the length (0 if stale /
 * internal address / not a bootstrap / on error).
 *
 * # Safety
 * `link` is a C-string; `out` is at least `out_cap` bytes.
 */
size_t mt_deeplink_bootstrap_endpoint(const char *link,
                                         uint64_t now_unix,
                                         uint8_t *out,
                                         size_t out_cap);

/**
 * Connect to the Mainline DHT (public BitTorrent bootstrap nodes). Released by
 * `mt_rvdht_free`. Null on error.
 */
RvDht *mt_rvdht_client(void);

/**
 * # Safety
 * `dht` is a pointer from `mt_rvdht_client` (not used after free) or null.
 */
void mt_rvdht_free(RvDht *dht);

/**
 * Resolves a friend rendezvous record by `dk`(32)+`salt`(20) from the DHT, writes the first
 * globally routable endpoint (SSRF-filtered, "host:port") to `out`;
 * returns the length (0 if there is no record / it is stale / only internal addresses / on error).
 *
 * # Safety
 * `dht` is valid; `dk` is at least 32 B; `salt` is at least 20 B; `friend_account_id` is at least 32 B or null
 * (null skips the §595 check -- not recommended); `out` is at least `out_cap` bytes.
 */
size_t mt_rvdht_resolve(const RvDht *dht,
                           const uint8_t *dk,
                           const uint8_t *salt,
                           const uint8_t *friend_account_id,
                           uint64_t now_unix,
                           uint8_t *out,
                           size_t out_cap);

uint32_t mt_abi_version(void);

int mt_mnemonic_to_master_seed(const char *mnemonic_utf8, uint8_t *out_master_seed);

int mt_mnemonic_to_entropy(const char *mnemonic_utf8, uint8_t *out_entropy);

int mt_mldsa_seed_for_role(const uint8_t *master_seed,
                           const uint8_t *role,
                           size_t role_len,
                           uint8_t *out_seed);

int mt_mldsa_keypair_from_seed(const uint8_t *seed, uint8_t *out_pubkey, uint8_t *out_seckey);

int mt_seed_keys(const char *mnemonic_utf8, uint8_t *out_pubkey, uint8_t *out_seckey);

/**
 * 24-word mnemonic -> ML-DSA-65 account keypair + canonical account_id (suite 0x0001).
 */
int mt_account_from_mnemonic(const char *mnemonic_utf8,
                             uint8_t *out_pubkey,
                             uint8_t *out_seckey,
                             uint8_t *out_account_id);



int mt_sign(const uint8_t *seckey, const uint8_t *msg, size_t msg_len, uint8_t *out_sig);

int mt_verify(const uint8_t *pubkey, const uint8_t *msg, size_t msg_len, const uint8_t *sig);

/**
 * 32 bytes of entropy -> 24-word UTF-8 mnemonic.
 *
 * `out_mnemonic_utf8` is a buffer of at least out_capacity bytes; the function writes a NUL-terminated string.
 * `out_len` is the number of bytes actually written (without the terminator). If the buffer is too small it returns MT_ERR_BUFFER_TOO_SMALL.
 */

/**
 * HKDF-Expand(master_seed, role, 64) -> ML-KEM-768 seed (d‖z). Stage 1: app_kem_key.
 */
int mt_mlkem_seed_for_role(const uint8_t *master_seed,
                           const uint8_t *role,
                           size_t role_len,
                           uint8_t *out_seed);

/**
 * ML-KEM-768 KeyGen from a 64-byte seed (FIPS 203, deterministic). pk 1184 / sk 2400.
 */
int mt_mlkem_keypair_from_seed(const uint8_t *seed, uint8_t *out_pubkey, uint8_t *out_seckey);

/**
 * ML-KEM-768 Encapsulate (FIPS 203 §6.2). pk 1184 -> ct 1088 / ss 32.
 */
int mt_mlkem_encaps(const uint8_t *pubkey, uint8_t *out_ct, uint8_t *out_ss);

/**
 * ML-KEM-768 Decapsulate (FIPS 203 §6.3, implicit-rejection). sk 2400, ct 1088 -> ss 32.
 */
int mt_mlkem_decaps(const uint8_t *seckey, const uint8_t *ct, uint8_t *out_ss);

/**
 * 24-word mnemonic -> app_kem_key (ML-KEM-768) via role "mt-app-encryption-key". pk 1184 / sk 2400.
 */
int mt_app_kem_from_mnemonic(const char *mnemonic_utf8,
                             uint8_t *out_pubkey,
                             uint8_t *out_seckey);

/**
 * history_key = HKDF-SHA-256(salt=0×32, ikm=entropy_32, info="mt-history-key", 32) -- messenger Stage 10.
 * `entropy` is 32 bytes; `out` is 32 bytes. SSOT for history_key across all clients.
 */
int mt_history_key(const uint8_t *entropy,
                   uint8_t *out);

/**
 * media_key = HKDF-SHA-256(0×32, entropy_32, "mt-media-key", 32) -- s.2 Stage 1.
 * A separate seed branch for media at rest (not history_key). `entropy`/`out` are 32 bytes.
 */
int mt_media_key(const uint8_t *entropy,
                 uint8_t *out);

/**
 * Release a buffer handed out by the mt_e2e_* functions.
 *
 * # Safety
 * `ptr`/`len` are exactly what mt_e2e_* returned via its out-parameters; call once.
 */
void mt_e2e_free(uint8_t *ptr,
                 size_t len);

/**
 * RatchetEncrypt via an opaque session blob. Returns a new session blob + the message.
 *
 * # Safety
 * All pointers are valid for their length; `rng_seed` is 64 bytes; out-pointers are non-null.
 */
int mt_e2e_encrypt(const uint8_t *session,
                   size_t session_len,
                   const uint8_t *pt,
                   size_t pt_len,
                   const uint8_t *rng_seed,
                   uint8_t **out_session,
                   size_t *out_session_len,
                   uint8_t **out_msg,
                   size_t *out_msg_len);

/**
 * RatchetDecrypt via an opaque session blob. Returns a new blob + the plaintext.
 *
 * # Safety
 * All pointers are valid for their length; out-pointers are non-null.
 */
int mt_e2e_decrypt(const uint8_t *session,
                   size_t session_len,
                   const uint8_t *msg,
                   size_t msg_len,
                   uint8_t **out_session,
                   size_t *out_session_len,
                   uint8_t **out_pt,
                   size_t *out_pt_len);

/**
 * Alice's side: handshake + session initialisation. Returns InitialHandshake
 * + the initiator session blob. `account_seed` is 32 bytes (the ML-DSA identity seed).
 *
 * # Safety
 * All key pointers are valid for the spec sizes; opk_* are read only when opk_flag=1.
 */
int mt_e2e_build_handshake(const uint8_t *alice_account_pub,
                           const uint8_t *account_seed,
                           const uint8_t *bob_account_pub,
                           const uint8_t *bob_app_kem_pub,
                           const uint8_t *bob_spk_pub,
                           uint32_t spk_id,
                           uint8_t opk_flag,
                           uint32_t opk_id,
                           const uint8_t *bob_opk_pub,
                           const uint8_t *eph_seed,
                           uint64_t send_time,
                           uint8_t **out_hs,
                           size_t *out_hs_len,
                           uint8_t **out_session,
                           size_t *out_session_len);

/**
 * Bob's side: handshake processing + recipient session initialisation.
 *
 * # Safety
 * All key pointers are valid for the spec sizes; opk_* are read only when opk_flag=1.
 */
int mt_e2e_process_handshake(const uint8_t *hs,
                             size_t hs_len,
                             const uint8_t *bob_account_id,
                             const uint8_t *bob_app_kem_pub,
                             const uint8_t *bob_app_kem_sk,
                             const uint8_t *bob_spk_pub,
                             const uint8_t *bob_spk_sk,
                             uint8_t opk_flag,
                             const uint8_t *bob_opk_pub,
                             const uint8_t *bob_opk_sk,
                             uint64_t now,
                             uint64_t accept_skew,
                             uint8_t **out_session,
                             size_t *out_session_len);

/**
 * Seal a media blob: sealed_blob = nonce || Seal(blob_key, nonce, input, AD=mt-media).
 * out is an owned buffer (release with mt_e2e_free). `input` is already final (padded to pad_len before the call).
 *
 * # Safety
 * blob_key is 32 bytes, nonce is 12 bytes, input is input_len bytes; out_ptr/out_len are non-null.
 */
int mt_e2e_seal_blob(const uint8_t *blob_key,
                     const uint8_t *nonce,
                     const uint8_t *input,
                     size_t input_len,
                     uint8_t **out_ptr,
                     size_t *out_len);

/**
 * blob_id = SHA-256(sealed_blob) -> out32 (32 bytes).
 *
 * # Safety
 * sealed_blob is len bytes; out32 is 32 bytes.
 */
int mt_e2e_blob_id(const uint8_t *sealed_blob, size_t len, uint8_t *out32);

/**
 * Decrypt a blob -> padded plaintext (owned; the caller truncates to size). Error -> MT_ERR_KEM_FAILED.
 *
 * # Safety
 * blob_key is 32 bytes; sealed_blob is len bytes; out_ptr/out_len are non-null.
 */
int mt_e2e_open_blob(const uint8_t *blob_key,
                     const uint8_t *sealed_blob,
                     size_t len,
                     uint8_t **out_ptr,
                     size_t *out_len);

/**
 * pad_len(n) is the target size after padding (hides the size).
 */
size_t mt_e2e_pad_len(size_t n);

/**
 * safety_number(id_A, id_B) -> 60 ASCII digits (Stage 8). Both pointers are 32-byte account_id;
 * the output is an owned buffer (60 bytes), release with mt_e2e_free.
 *
 * # Safety
 * `id_a`/`id_b` are valid for 32 bytes; out-pointers are non-null.
 */
int mt_e2e_safety_number(const uint8_t *id_a,
                         const uint8_t *id_b,
                         uint8_t **out_ptr,
                         size_t *out_len);

/**
 * party_code(account_id) -> 30 ASCII digits (Stage 8). The pointer is 32 bytes; the output is owned.
 *
 * # Safety
 * `id` is valid for 32 bytes; out-pointers are non-null.
 */
int mt_e2e_party_code(const uint8_t *id,
                      uint8_t **out_ptr,
                      size_t *out_len);

/**
 * call_key/sframe_key (Stage 13, PQ media layer of a call). `call_seed` is 32 bytes (from the E2E signal);
 * out is 64 bytes: call_key(32) ‖ sframe_key(32).
 *
 * # Safety
 * `call_seed` is valid for 32 bytes; `out` for 64 bytes.
 */
int mt_e2e_call_key(const uint8_t *call_seed,
                    uint8_t *out);

/**
 * Encodes WakeInline (recv_id 32 + window 8 LE) to `out` (40 B). true on success.
 *
 * # Safety
 * `recv_id` is valid and at least 32 B; `out` is valid and at least 40 B.
 */
bool mt_wake_inline_encode(const uint8_t *recv_id, uint64_t window, uint8_t *out);

/**
 * Decodes WakeInline from `input` (len B). On success writes recv_id (32) + window.
 *
 * # Safety
 * `input` is valid and at least `len` B; `out_recv_id` is at least 32 B; `out_window` is valid.
 */
bool mt_wake_inline_decode(const uint8_t *input,
                           size_t len,
                           uint8_t *out_recv_id,
                           uint64_t *out_window);

/**
 * Encodes WakeHandle (wake_handle 16 + window 8 LE) to `out` (24 B). true on success.
 *
 * # Safety
 * `handle` is valid and at least 16 B; `out` is valid and at least 24 B.
 */
bool mt_wake_handle_encode(const uint8_t *handle,
                           uint64_t window,
                           uint8_t *out);

/**
 * Decodes WakeHandle from `input` (len B). On success writes wake_handle (16) + window.
 *
 * # Safety
 * `input` is valid and at least `len` B; `out_handle` is at least 16 B; `out_window` is valid.
 */
bool mt_wake_handle_decode(const uint8_t *input,
                           size_t len,
                           uint8_t *out_handle,
                           uint64_t *out_window);

/**
 * Tier arbiter: returns the tier number 1-4 (highest sovereignty first).
 */
uint8_t mt_wake_select_rung(bool live_tunnel,
                            bool ibeacon_home,
                            bool unlock_sync);

/**
 * Creates an account_id↔wake_handle registry (for a phone postman). Released
 * `mt_wake_registry_free`.
 */
WakeRegistry *mt_wake_registry_new(void);

/**
 * # Safety
 * `reg` is a pointer from `mt_wake_registry_new` (not used after free) or null.
 */
void mt_wake_registry_free(WakeRegistry *reg);

/**
 * Registers account_id (32 B), writes the 16 B wake_handle. Idempotent. true on success.
 *
 * # Safety
 * `reg` is valid; `account_id` is at least 32 B; `out_handle` is at least 16 B.
 */
bool mt_wake_register(WakeRegistry *reg,
                      const uint8_t *account_id,
                      uint8_t *out_handle);

/**
 * Looks up wake_handle by account_id. true if found (writes out_handle), otherwise false.
 *
 * # Safety
 * `reg` is valid; `account_id` is at least 32 B; `out_handle` is at least 16 B.
 */
bool mt_wake_handle_of(const WakeRegistry *reg,
                       const uint8_t *account_id,
                       uint8_t *out_handle);


/**
 * Derives queue keys from routing_secret(32)+queue_index -- recv/send ML-DSA keypairs.
 * out_recv_pk[1952] out_recv_sk[4032] out_send_pk[1952] out_send_sk[4032]. 0=success, -1=error.
 *
 * # Safety
 * routing_secret → 32 B; out_* are valid buffers of the stated sizes.
 */
int32_t mt_muq_derive_queue_keys(const uint8_t *routing_secret,
                                 uint64_t queue_index,
                                 uint8_t *out_recv_pk,
                                 uint8_t *out_recv_sk,
                                 uint8_t *out_send_pk,
                                 uint8_t *out_send_sk);

/**
 * Serializes a Queue (wire §413) for registration. send_pk null = unsecured queue.
 * Returns the bytes written (QUEUE_WIRE_SIZE) or 0 on error / small buffer.
 *
 * # Safety
 * recv_id/send_id/recv_pk → 32/32/1952; send_pk → 1952 or null; out → out_cap bytes.
 */
size_t mt_muq_queue_serialize(const uint8_t *recv_id,
                                 const uint8_t *send_id,
                                 const uint8_t *recv_pk,
                                 const uint8_t *send_pk,
                                 uint64_t rotation_epoch,
                                 uint32_t quota,
                                 uint8_t *out,
                                 size_t out_cap);

/**
 * Random QueueId (32 B, OS CSPRNG) -- recv_id or send_id. 0=success, -1=error.
 *
 * # Safety
 * out is valid for 32 bytes.
 */
int32_t mt_muq_gen_queue_id(uint8_t *out);

/**
 * Node hello (serverless automaton): connect to node addr, obtain the capability --
 * host_kem (1184 B into out_kem) + send_id (32 B into out_send_id). The sender finds the
 * peer node via mDNS and learns where to deposit, without a map. 0=success, -1=error.
 */
int32_t mt_node_hello(const char *addr, uint8_t *out_kem, uint8_t *out_send_id);


// Stage 1 of the second front -- local archive (per-chat folders of the Montana archive)
int32_t mt_archive_append(const char *base_path, const char *chat_name,
                          const uint8_t *hk, const uint8_t *account_id,
                          const uint8_t *device_id,
                          const uint8_t *conv_id, uint8_t dir,
                          uint64_t send_time, const uint8_t *content, size_t content_len);
// Stage 2 -- ArchiveRoot over the whole local archive (fingerprint for anchor/convergence), 32 bytes into out
int32_t mt_archive_root(const char *base_path, const uint8_t *hk,
                        const uint8_t *account_id, uint8_t *out);
// Stages 3-4 -- block replication of the archive (ArchiveRoot convergence between devices)
int32_t mt_writer_tag(const uint8_t *device_id, uint8_t *out);
int32_t mt_archive_block_id(const uint8_t *sealed, size_t sealed_len,
                            uint8_t *out_writer_tag, uint64_t *out_block_seq);
intptr_t mt_archive_export(const char *base_path, const char *chat_name,
                           const uint8_t *writer_tag, uint64_t from_seq,
                           uint8_t *out, size_t out_cap);
int32_t mt_archive_ingest(const char *base_path, const char *chat_name,
                          const uint8_t *hk, const uint8_t *account_id,
                          const uint8_t *sealed, size_t sealed_len);
int32_t mt_archive_peek_conv(const uint8_t *hk, const uint8_t *account_id,
                             const uint8_t *sealed, size_t sealed_len, uint8_t *out);
intptr_t mt_archive_open_block(const uint8_t *hk, const uint8_t *account_id,
                               const uint8_t *sealed, size_t sealed_len,
                               uint8_t *out, size_t out_cap);
int32_t mt_archive_put_media(const char *base_path, const char *chat_name,
                             const char *blob_id_hex, const uint8_t *hk, const uint8_t *account_id,
                             const uint8_t *blob, size_t blob_len);
intptr_t mt_archive_get_media(const char *base_path, const char *chat_name,
                              const char *blob_id_hex, const uint8_t *hk, const uint8_t *account_id,
                              uint8_t *out, size_t out_cap);

#endif  /* MONTANA_FFI_H */
