[package]
name = "mt-derive"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mt-codec = { workspace = true }
mt-genesis = { workspace = true }
mt-proof = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
mt-conformance = { path = "../mt-conformance" }
