#!/usr/bin/env python3
"""Regenerate the "Latest changes" section of README.md from CHANGELOG.md.

Whoever changes CHANGELOG.md runs this script and commits README.md in the same commit, so the README never
lags behind the log. `--check` changes nothing and exits 1 when the README is behind the log.

The section lies between the two markers below; everything outside them is left as it is.
Standard library only.
"""
import datetime
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- latest changes: generated by tools/readme-sync.py from CHANGELOG.md, do not edit by hand -->"
END = "<!-- latest changes end -->"
MARKER = re.compile(r"<!-- montana-change (\{[^\n]+\}) -->")
# a record that names a build of its own opens its build field with it: "Debug 2070", "1983 built ..."; a field that
# opens with "2069 tree" or "2070 source" names the tree a change was made on, not a build
BUILT = re.compile(r"^((?:Debug |Release )?\d{4})\b(?! (?:tree|source))")
PUBLISHED = re.compile(r"^## (\S+) \((\d+)\) — (\d{4}-\d{2}-\d{2}), (.+)$", re.M)
SHOWN = 5


def when(utc):
    return datetime.datetime.fromisoformat(utc).astimezone(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def headline(summary, limit=160):
    text = re.split(r": |; ", summary.strip(), maxsplit=1)[0].rstrip(" .")
    if len(text) > limit:
        text = text[:limit].rsplit(" ", 1)[0].rstrip(",;: ") + "…"
    return text


def section(log):
    records = [json.loads(m[1]) for m in MARKER.finditer(log)]
    live = [r for r in records if not r.get("withdrawn")]
    if not live:
        raise ValueError("CHANGELOG.md holds no change record")
    built = next(((BUILT.match(str(r.get("build", ""))), r) for r in live if BUILT.match(str(r.get("build", "")))), None)
    tail = log.split("\n## Published builds\n", 1)
    published = PUBLISHED.search(tail[1]) if len(tail) == 2 else None
    rows = ["| | |", "|---|---|", "| Log updated | " + when(live[0]["utc"]) + " |"]
    if built:
        rows.append("| Newest build in the log | " + built[0][1] + ", " + when(built[1]["utc"]) + " |")
    if published:
        rows.append("| Latest build in the published list | %s (%s), %s, %s |" % published.groups())
    lines = [BEGIN, "## Latest changes", "",
             "Generated from [CHANGELOG.md](CHANGELOG.md) by `tools/readme-sync.py`, in the same commit as the log.", ""]
    lines += rows + [""]
    for r in live[:SHOWN]:
        bound = ("commit `" + r["commit"][:12] + "`") if r.get("commit") else "commit pending"
        lines.append("- **" + when(r["utc"]) + "** — " + headline(r["summary"]) + " (" + bound + ")")
    lines += ["", "The full record of every change, with its build, system and source tree, is in the log.", END]
    return "\n".join(lines)


def main(argv):
    check = argv[1:] == ["--check"]
    if argv[1:] and not check:
        print("usage: python3 tools/readme-sync.py [--check]", file=sys.stderr)
        return 2
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    if text.count(BEGIN) != 1 or text.count(END) != 1 or text.index(BEGIN) > text.index(END):
        print("README.md must hold the latest-changes markers exactly once, in order", file=sys.stderr)
        return 2
    fresh = section((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"))
    head, rest = text.split(BEGIN, 1)
    new = head + fresh + rest.split(END, 1)[1]
    if new == text:
        print("README.md: latest changes match CHANGELOG.md")
        return 0
    if check:
        print("README.md: latest changes are behind CHANGELOG.md; run python3 tools/readme-sync.py", file=sys.stderr)
        return 1
    readme.write_text(new, encoding="utf-8")
    print("README.md: latest changes regenerated from CHANGELOG.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
